### ISSUE TITLE
QRules fails with particle v1 charge fractions

### ISSUE THREAD

**Issue by redeboer** [ComPWA/qrules#334]
[`particle` v1](https://github.com/scikit-hep/particle/releases/tag/v1.0.0) changed the type of charge values from `float` to `fractions.Fraction`. QRules currently assumes that `item.charge` behaves like a float and calls `item.charge.is_integer()` while loading the PDG particle definitions.

https://github.com/ComPWA/qrules/blob/f3f25b27a44acb0136e0aca237cbf061f3bf5cad/src/qrules/particle.py#L507

Also, the spin `J` of the particle is now sometimes `None`, which is a problem here:

https://github.com/ComPWA/qrules/blob/f3f25b27a44acb0136e0aca237cbf061f3bf5cad/src/qrules/particle.py#L559

This came up while updating the dependency lock file to `particle` v1 in #333.

## How to reproduce?

Use Python 3.10 for the reproducer, because newer Python versions can mask this via `Fraction.is_integer()`.

This works on `main` with `particle==0.26.2`:

```bash
uv run --python 3.10 --with particle==0.26.2 python - <<'PY'
from importlib.metadata import version
from qrules.particle import load_pdg

print(f"particle {version('particle')}")
print(len(load_pdg()))
PY
```

Expected output:

```text
particle 0.26.2
541
```

This crashes on `main` with `particle==1.0.0`:

```bash
uv run --python 3.10 --with particle==1.0.0 python - <<'PY'
from importlib.metadata import version
from qrules.particle import load_pdg

print(f"particle {version('particle')}")
print(len(load_pdg()))
PY
```

Expected failure:

```text
particle 1.0.0
AttributeError: 'Fraction' object has no attribute 'is_integer'
```
